### ISSUE TITLE
Not sure how to get rainbow tile markers to work

### ISSUE THREAD

**Issue by rennteaa** [geheur/rainbow-rave#1]
Hi! I really want to use this plugin so I can have rainbow tile markers/indicators. However, when I enable that setting it doesn't seem to work. (looks like the default) Is there something I am doing wrong or is the plugin not working? 

also sorry im not sure how github works haha

**Comment by dusty-dusty** [comment]
Just had this issue, you have to turn on "remember color per tile" in ground markers

**Comment by geheur** [comment]
that option no longer exists so this issue is probably not relevant anymore.
