### ISSUE TITLE
Certain aspects of the plugin not working since about 2 days ago.

### ISSUE THREAD

**Issue by Kwazix** [geheur/rainbow-rave#15]
Certain features arn't working anymore. Most notably. Tile markers no longer turn rainbow.

**Comment by geheur** [comment]
what else? I don't use this plugin.

**Comment by Kwazix** [comment]
So far ive only noticed the tile marking feature.

**Comment by geheur** [comment]
ah I see. so it's for new tiles. That makes sense given that runelite changed ground markers recently.

**Comment by Kwazix** [comment]
I cant confirm because im not at home. But i think setting a tile marker and then logging out and then back in, caused it to work properly.
________________________________

**Comment by geheur** [comment]
to be fixed in 1.2.8 https://github.com/runelite/plugin-hub/pull/4685 ty for reporting it.
