### ISSUE TITLE
Issue when displaying overlay on coins

### ISSUE THREAD

**Issue by Felanbird** [geheur/rainbow-rave#19]
Coins no longer have a GE/HA value attached to them (honestly they never should have since what's the point), but because of this rainbow-rave's overlay is no longer the same as the normal ground items overlay, and it's causing a clipping issue.

![image](https://github.com/geheur/rainbow-rave/assets/41973452/350517c7-a5a4-403d-bab5-99c09ca2abeb)

**Comment by geheur** [comment]
https://github.com/runelite/plugin-hub/pull/6090
