### ISSUE TITLE
raibow mouse trail

### ISSUE THREAD

**Issue by pettrs** [geheur/rainbow-rave#4]
lots of people are having issues where if they enable another plugin from the pluginhub, the rainbow mouse trail auto enables. possibly set this to disabled by default as a temp solution? probably also disable other functions by default...

scythe swing is dope though!

**Comment by geheur** [comment]
yeah that's not a bad idea. People don't use this plugin to make the client more obnoxious like I originally expected lol.

**Comment by geheur** [comment]
the default is to have the mouse trail off.
