### ISSUE TITLE
Rainbow destination tile indicator

### ISSUE THREAD

**Issue by miikaok** [geheur/rainbow-rave#6]
It would be cool to have the destination tile as a rainbow. Would it be possible to make? Destination tile can be shown from the plugin called "tile indicators". There is also another one called "better tile indicators".

![0VoRMA8](https://user-images.githubusercontent.com/58865894/177042757-1b6357a3-139d-43f7-ae5c-d8046c603d31.png)

**Comment by geheur** [comment]
I think I added this.
